name: "sequential-dispatcher"
description: "Dispatch another workflow and optionally wait for completion"

branding:
  icon: play
  color: blue

inputs:
  workflow_file:
    description: "Path to the workflow file inside .github/workflows (e.g., .github/workflows/build.yml)"
    required: true
  ref:
    description: "Git ref to run (branch or tag)"
    required: false
    default: "main"
  wait:
    description: "Wait for the dispatched workflow to complete"
    required: false
    default: "true"
  timeout-seconds:
    description: "Max seconds to wait for completion"
    required: false
    default: "7200"
  poll-interval-seconds:
    description: "Polling interval in seconds"
    required: false
    default: "10"
  label:
    description: "Human-friendly label for logs"
    required: false
    default: "Sequential Dispatcher"
  token:
    description: "GitHub token (defaults to GITHUB_TOKEN)"
    required: false

outputs:
  run_id:
    description: "Dispatched workflow run id"
    value: ${{ steps.wait.outputs.run_id }}
  conclusion:
    description: "Conclusion of the completed workflow"
    value: ${{ steps.wait.outputs.conclusion }}

runs:
  using: "composite"
  steps:
    - name: Ensure jq
      shell: bash
      run: |
        if ! command -v jq >/dev/null 2>&1; then
          sudo apt-get update -y
          sudo apt-get install -y jq
        fi

    - name: Dispatch workflow
      id: dispatch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: |
        set -euo pipefail
        WORKFLOW_FILE='${{ inputs.workflow_file }}'
        REF='${{ inputs.ref }}'
        LABEL='${{ inputs.label }}'
        API="${GITHUB_API_URL:-https://api.github.com}"
        OWNER_REPO="${GITHUB_REPOSITORY}"
        echo "Dispatching: $LABEL ($WORKFLOW_FILE) on ref=$REF"
        curl -sSL -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$API/repos/$OWNER_REPO/actions/workflows/$(basename "$WORKFLOW_FILE")/dispatches" \
          -d "{\"ref\":\"$REF\"}"

    - name: Wait for completion
      id: wait
      if: ${{ inputs.wait == 'true' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: |
        set -euo pipefail
        WORKFLOW_FILE='${{ inputs.workflow_file }}'
        REF='${{ inputs.ref }}'
        API="${GITHUB_API_URL:-https://api.github.com}"
        OWNER_REPO="${GITHUB_REPOSITORY}"
        TIMEOUT='${{ inputs.timeout-seconds }}'
        INTERVAL='${{ inputs.poll-interval-seconds }}'
        echo "Waiting for workflow run to start..."
        # Find most recent run for this workflow and ref triggered by workflow_dispatch
        run_id=""
        start_time=$(date +%s)
        while :; do
          runs_json="$(curl -sSL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            "$API/repos/$OWNER_REPO/actions/workflows/$(basename "$WORKFLOW_FILE")/runs?event=workflow_dispatch&branch=$REF&per_page=5")"
          run_id=$(echo "$runs_json" | jq -r '.workflow_runs | sort_by(.created_at) | reverse | .[0].id')
          if [ -n "$run_id" ] && [ "$run_id" != "null" ]; then
            break
          fi
          now=$(date +%s)
          elapsed=$((now - start_time))
          if [ "$elapsed" -ge "$TIMEOUT" ]; then
            echo "Timed out waiting for dispatched run to appear" >&2
            exit 1
          fi
          sleep "$INTERVAL"
        done
        echo "Run id: $run_id"
        echo "run_id=$run_id" >> "$GITHUB_OUTPUT"
        echo "Polling run status until completion..."
        while :; do
          run_json=$(curl -sSL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            "$API/repos/$OWNER_REPO/actions/runs/$run_id")
          status=$(echo "$run_json" | jq -r .status)
          conclusion=$(echo "$run_json" | jq -r .conclusion)
          echo "status=$status conclusion=$conclusion"
          if [ "$status" = "completed" ]; then
            echo "conclusion=$conclusion" >> "$GITHUB_OUTPUT"
            test "$conclusion" = "success"
            exit $?
          fi
          now=$(date +%s)
          elapsed=$((now - start_time))
          if [ "$elapsed" -ge "$TIMEOUT" ]; then
            echo "Timed out waiting for run $run_id to complete" >&2
            exit 1
          fi
          sleep "$INTERVAL"
        done
